baseURL = "https://promhippie.github.io/prometheus-hcloud-sd/"
languageCode = "en-us"
title = "Prometheus HetznerCloud SD"
pygmentsUseClasses = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Prometheus service discovery for HetznerCloud"
  keywords = "prometheus, sd, service, discovery, hetzner, cloud"
